// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/sensu/core/v2/fallback_pipelines.proto

package v2

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// FallbackPipelines represents a named collection of pipeline workflows.
type FallbackPipelines struct {
	// Metadata contains the name, namespace, labels and annotations of the
	// fallback pipelines.
	ObjectMeta `protobuf:"bytes,1,opt,name=Metadata,proto3,embedded=Metadata" json:"metadata,omitempty"`
	// Pipelines contains one or more fallback pipelines.
	Pipelines            []*Pipeline `protobuf:"bytes,2,rep,name=Pipelines,proto3" json:"pipelines" yaml: "pipelines"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FallbackPipelines) Reset()         { *m = FallbackPipelines{} }
func (m *FallbackPipelines) String() string { return proto.CompactTextString(m) }
func (*FallbackPipelines) ProtoMessage()    {}
func (*FallbackPipelines) Descriptor() ([]byte, []int) {
	return fileDescriptor_99a0dfc9a73e2ae8, []int{0}
}
func (m *FallbackPipelines) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FallbackPipelines) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FallbackPipelines.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FallbackPipelines) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FallbackPipelines.Merge(m, src)
}
func (m *FallbackPipelines) XXX_Size() int {
	return m.Size()
}
func (m *FallbackPipelines) XXX_DiscardUnknown() {
	xxx_messageInfo_FallbackPipelines.DiscardUnknown(m)
}

var xxx_messageInfo_FallbackPipelines proto.InternalMessageInfo

func (m *FallbackPipelines) GetPipelines() []*Pipeline {
	if m != nil {
		return m.Pipelines
	}
	return nil
}

func init() {
	proto.RegisterType((*FallbackPipelines)(nil), "sensu.core.v2.FallbackPipelines")
}

func init() {
	proto.RegisterFile("github.com/sensu/core/v2/fallback_pipelines.proto", fileDescriptor_99a0dfc9a73e2ae8)
}

var fileDescriptor_99a0dfc9a73e2ae8 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4c, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x2f, 0x4e, 0xcd, 0x2b, 0x2e, 0xd5, 0x4f, 0xce, 0x2f,
	0x4a, 0xd5, 0x2f, 0x33, 0xd2, 0x4f, 0x4b, 0xcc, 0xc9, 0x49, 0x4a, 0x4c, 0xce, 0x8e, 0x2f, 0xc8,
	0x2c, 0x48, 0xcd, 0xc9, 0xcc, 0x4b, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x05,
	0xab, 0xd3, 0x03, 0xa9, 0xd3, 0x2b, 0x33, 0x92, 0x32, 0x41, 0x32, 0x21, 0x3d, 0x3f, 0x3d, 0x5f,
	0x1f, 0xac, 0x2a, 0xa9, 0x34, 0xcd, 0xa1, 0xcc, 0x50, 0xcf, 0x58, 0xcf, 0x08, 0x2c, 0x08, 0x16,
	0x03, 0xb3, 0x20, 0x86, 0x48, 0x29, 0xe3, 0xb4, 0x37, 0x37, 0xb5, 0x24, 0x11, 0xaa, 0x48, 0x1d,
	0xa7, 0x22, 0x98, 0x9b, 0x20, 0x0a, 0x95, 0x8e, 0x32, 0x72, 0x09, 0xba, 0x41, 0xdd, 0x1b, 0x00,
	0x73, 0xae, 0x50, 0x28, 0x17, 0x87, 0x6f, 0x6a, 0x49, 0x62, 0x4a, 0x62, 0x49, 0xa2, 0x04, 0xa3,
	0x02, 0xa3, 0x06, 0xb7, 0x91, 0xa4, 0x1e, 0x8a, 0xdb, 0xf5, 0xfc, 0x93, 0xb2, 0x52, 0x93, 0x4b,
	0x40, 0x8a, 0x9c, 0xe4, 0x4e, 0xdc, 0x93, 0x67, 0xb8, 0x70, 0x4f, 0x9e, 0xf1, 0xd5, 0x3d, 0x79,
	0xa1, 0x5c, 0xa8, 0x36, 0x9d, 0xfc, 0xdc, 0xcc, 0x92, 0xd4, 0xdc, 0x82, 0x92, 0xca, 0x20, 0xb8,
	0x51, 0x42, 0x91, 0x5c, 0x9c, 0x70, 0x3b, 0x24, 0x98, 0x14, 0x98, 0x35, 0xb8, 0x8d, 0xc4, 0xd1,
	0xcc, 0x85, 0xc9, 0x3b, 0x29, 0xbd, 0xba, 0x27, 0xcf, 0x09, 0x0f, 0xc0, 0x4f, 0xf7, 0xe4, 0x05,
	0x2b, 0x13, 0x73, 0x73, 0xac, 0x14, 0x94, 0xe0, 0x62, 0x4a, 0x41, 0x08, 0xd3, 0x9c, 0x14, 0x7e,
	0x3c, 0x94, 0x63, 0x5c, 0xf1, 0x48, 0x8e, 0x71, 0xc7, 0x23, 0x39, 0xc6, 0x13, 0x8f, 0xe4, 0x18,
	0x2f, 0x3c, 0x92, 0x63, 0x7c, 0xf0, 0x48, 0x8e, 0x71, 0xc6, 0x63, 0x39, 0x86, 0x28, 0xa6, 0x32,
	0xa3, 0x24, 0x36, 0xb0, 0x87, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xe4, 0xaf, 0x83,
	0xb8, 0x01, 0x00, 0x00,
}

func (m *FallbackPipelines) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FallbackPipelines) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FallbackPipelines) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Pipelines) > 0 {
		for iNdEx := len(m.Pipelines) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pipelines[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFallbackPipelines(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFallbackPipelines(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintFallbackPipelines(dAtA []byte, offset int, v uint64) int {
	offset -= sovFallbackPipelines(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedFallbackPipelines(r randyFallbackPipelines, easy bool) *FallbackPipelines {
	this := &FallbackPipelines{}
	v1 := NewPopulatedObjectMeta(r, easy)
	this.ObjectMeta = *v1
	if r.Intn(5) != 0 {
		v2 := r.Intn(5)
		this.Pipelines = make([]*Pipeline, v2)
		for i := 0; i < v2; i++ {
			this.Pipelines[i] = NewPopulatedPipeline(r, easy)
		}
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedFallbackPipelines(r, 3)
	}
	return this
}

type randyFallbackPipelines interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneFallbackPipelines(r randyFallbackPipelines) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringFallbackPipelines(r randyFallbackPipelines) string {
	v3 := r.Intn(100)
	tmps := make([]rune, v3)
	for i := 0; i < v3; i++ {
		tmps[i] = randUTF8RuneFallbackPipelines(r)
	}
	return string(tmps)
}
func randUnrecognizedFallbackPipelines(r randyFallbackPipelines, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldFallbackPipelines(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldFallbackPipelines(dAtA []byte, r randyFallbackPipelines, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateFallbackPipelines(dAtA, uint64(key))
		v4 := r.Int63()
		if r.Intn(2) == 0 {
			v4 *= -1
		}
		dAtA = encodeVarintPopulateFallbackPipelines(dAtA, uint64(v4))
	case 1:
		dAtA = encodeVarintPopulateFallbackPipelines(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateFallbackPipelines(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateFallbackPipelines(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateFallbackPipelines(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateFallbackPipelines(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (this *FallbackPipelines) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FallbackPipelines)
	if !ok {
		that2, ok := that.(FallbackPipelines)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ObjectMeta.Equal(&that1.ObjectMeta) {
		return false
	}
	if len(this.Pipelines) != len(that1.Pipelines) {
		return false
	}
	for i := range this.Pipelines {
		if !this.Pipelines[i].Equal(that1.Pipelines[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (m *FallbackPipelines) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovFallbackPipelines(uint64(l))
	if len(m.Pipelines) > 0 {
		for _, e := range m.Pipelines {
			l = e.Size()
			n += 1 + l + sovFallbackPipelines(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovFallbackPipelines(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFallbackPipelines(x uint64) (n int) {
	return sovFallbackPipelines(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FallbackPipelines) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFallbackPipelines
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FallbackPipelines: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FallbackPipelines: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFallbackPipelines
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFallbackPipelines
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFallbackPipelines
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pipelines", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFallbackPipelines
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFallbackPipelines
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFallbackPipelines
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pipelines = append(m.Pipelines, &Pipeline{})
			if err := m.Pipelines[len(m.Pipelines)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFallbackPipelines(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFallbackPipelines
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFallbackPipelines(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFallbackPipelines
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFallbackPipelines
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFallbackPipelines
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFallbackPipelines
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFallbackPipelines
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFallbackPipelines
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFallbackPipelines        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFallbackPipelines          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFallbackPipelines = fmt.Errorf("proto: unexpected end of group")
)
