version: 2.1

orbs:
  go: circleci/go@1.7.1

jobs:
  test:
    parameters:
      module:
        type: string
    working_directory: ~/core/<< parameters.module>>
    executor:
      name: go/default
      tag: '1.19'
    steps:
      - checkout:
          path: ~/core
      - go/load-cache
      - go/mod-download
      - run: go test -p 2 ./...
      - go/save-cache

workflows:
  main:
    jobs:
      - test:
          name: core/v2
          module: v2
      - test:
          name: core/v3
          module: v3
